# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129dWu84f5ztZCzE-1Cg4QK1oSPuAFRg1
"""

!pip install pandas numpy matplotlib seaborn scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

class PredictiveMaintenanceSystem:

    def __init__(self, filepath, last_digit):
        self.filepath = filepath
        self.last_digit = last_digit
        self.df = None
        self.unique_df = None

    def load_data(self):
        try:
            self.df = pd.read_csv(self.filepath)
            print("Data loaded successfully")
            print("Shape:", self.df.shape)
        except Exception as e:
            print("Load error:", e)

    def clean_data(self):
        try:
            self.df.drop_duplicates(inplace=True)
            self.df.fillna(self.df.mean(numeric_only=True), inplace=True)
            print("Data cleaned successfully")
        except Exception as e:
            print("Cleaning error:", e)

    def create_unique_df(self):
        try:
            self.unique_df = self.df[
                (self.df['Tool wear [min]'] % self.last_digit == 0) &
                (self.df['Target'] == 1)
            ].copy()

            self.unique_df.drop_duplicates(inplace=True)

            print("Unique dataset created")
            print("Shape:", self.unique_df.shape)

        except Exception as e:
            print("Unique filter error:", e)

    def analyze_statistics(self):
        try:
            data = self.unique_df.select_dtypes(include='number')

            print("Mean:\n", np.mean(data))
            print("\nMedian:\n", np.median(data))
            print("\nStd Dev:\n", np.std(data))
            print("\nVariance:\n", np.var(data))

        except Exception as e:
            print("Analysis error:", e)

    def compute_correlation(self):
        try:
            corr = self.unique_df.corr(numeric_only=True)
            print(corr)
            return corr
        except Exception as e:
            print("Correlation error:", e)

    def plot_correlation_heatmap(self):
        try:
            corr = self.unique_df.corr(numeric_only=True)

            plt.figure(figsize=(10,6))
            sns.heatmap(corr, annot=True)
            plt.title("Correlation Heatmap")
            plt.show()

        except Exception as e:
            print("Heatmap error:", e)

    def distribution_analysis(self):
        try:
            data = self.unique_df.select_dtypes(include='number')

            skewness = data.skew()
            print("Skewness:\n", skewness)

            q1 = data.quantile(0.25)
            q3 = data.quantile(0.75)
            iqr = q3 - q1
            data_range = data.max() - data.min()

            print("\nInterquartile Range (IQR):\n", iqr)
            print("\nRange:\n", data_range)

            outliers = {}

            for col in data.columns:
                lower_bound = q1[col] - 1.5 * iqr[col]
                upper_bound = q3[col] + 1.5 * iqr[col]

                outlier_count = data[(data[col] < lower_bound) | (data[col] > upper_bound)].shape[0]
                outliers[col] = outlier_count

            print("\nOutlier Count per Column:\n", outliers)

        except Exception as e:
            print("Distribution analysis error:", e)

    def static_graphs(self):

        try:

            # Histogram
            self.unique_df.hist(figsize=(12, 10))

            plt.suptitle("Histograms")

            plt.show()


            # Boxplot
            plt.figure(figsize=(12, 6))

            sns.boxplot(
                data=self.unique_df.select_dtypes(include=['number'])
            )

            plt.title("Boxplot")

            plt.xticks(rotation=45)

            plt.show()


            # Scatter Plot
            plt.figure(figsize=(8, 6))

            sns.scatterplot(
                x='Air temperature [K]',
                y='Process temperature [K]',
                hue='Failure Type',
                data=self.unique_df
            )

            plt.title("Air Temperature vs Process Temperature")

            plt.show()

        except Exception as e:
            print("Static graph error:\n", e)

    def animate_all(self):
        try:
            import matplotlib.pyplot as plt
            from matplotlib.animation import FuncAnimation

            temp_data = self.unique_df.groupby('Failure Type')['Air temperature [K]'].mean()
            wear_data = self.unique_df.groupby('Failure Type')['Tool wear [min]'].mean()

            fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

            ax1.set_title("Avg Air Temperature")
            ax1.set_ylim(0, temp_data.max() + 5)
            bars1 = ax1.bar(temp_data.index, [0] * len(temp_data))

            ax2.set_title("Avg Tool Wear")
            ax2.set_ylim(0, wear_data.max() + 5)
            bars2 = ax2.bar(wear_data.index, [0] * len(wear_data))

            def update(frame):
                for i, bar in enumerate(bars1):
                    bar.set_height(temp_data.values[i] * frame / 100)

                for i, bar in enumerate(bars2):
                    bar.set_height(wear_data.values[i] * frame / 100)

                return list(bars1) + list(bars2)

            ani = FuncAnimation(fig, update, frames=100, interval=20, blit=False)

            plt.close(fig)

            return ani

        except Exception as e:
            print("Animation error:", e)
            return None

system.load_data()
system.clean_data()
system.create_unique_df()

system.create_unique_df()
system.analyze_statistics()

system.create_unique_df()
system.distribution_analysis()

system.create_unique_df()
system.plot_correlation_heatmap()

system = PredictiveMaintenanceSystem(
    filepath="predictive_maintenance.csv",
    last_digit=6
)

system.load_data()
system.clean_data()
system.create_unique_df()
system.distribution_analysis()

system.static_graphs()

from IPython.display import HTML, display

system = PredictiveMaintenanceSystem(
    filepath="predictive_maintenance.csv",
    last_digit=6
)

system.load_data()
system.clean_data()
system.create_unique_df()
print("Data setup complete for animation.")

animation_to_display = system.animate_all()

if animation_to_display:
    display(HTML(animation_to_display.to_jshtml()))
else:
    print("Animation object was not created.")

features = [
    'Air temperature [K]',
    'Rotational speed [rpm]',
    'Torque [Nm]',
    'Tool wear [min]'
]

X = df[features]
y = df['Target']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Model trained successfully!")

from sklearn.metrics import accuracy_score, classification_report

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print("\nClassification Report:\n")
print(classification_report(y_test, pred))