# -*- coding: utf-8 -*-
"""MAIN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_er3G91mVTdsA6dQOXi99M-c_sthiri
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from matplotlib.animation import FuncAnimation
from IPython.display import HTML, display


class IRBRobotKinematicsSystem:

    def __init__(self, filepath, last_digit):
        self.filepath = filepath
        self.last_digit = 15
        self.df = None
        self.unique_df = None

    def load_data(self):
        try:
            self.df = pd.read_csv(self.filepath)
            print("Data loaded successfully")
            print("Shape:", self.df.shape)
        except Exception as e:
            print("Load error:", e)

    def clean_data(self):
        try:
            if self.df is None:
                print("Load data first!")
                return

            self.cleaned_df = self.df.copy()

            original_rows = len(self.cleaned_df)
            self.cleaned_df.drop_duplicates(inplace=True)
            rows_after_dedup = len(self.cleaned_df)

            missing_before_fill = self.cleaned_df.isnull().sum().sum()
            self.cleaned_df.fillna(
                self.cleaned_df.mean(numeric_only=True),
                inplace=True
            )
            missing_after_fill = self.cleaned_df.isnull().sum().sum()

            print("Data cleaned successfully")
            print(f"Original rows before cleaning: {original_rows}")
            print(f"Rows after removing duplicates: {rows_after_dedup}")
            print(f"Total missing values (before fill): {missing_before_fill}")
            print(f"Total missing values (after fill): {missing_after_fill}")
            print("Cleaned shape:", self.cleaned_df.shape)
        except Exception as e:
            print("Clean data error:", e)

    def create_unique_df(self):
        try:
            self.unique_df = self.df[self.df.index % self.last_digit == 0].copy()
            print("Unique dataset created using ID-based filtering")
            print("Shape:", self.unique_df.shape)
        except Exception as e:
            print("Unique filter error:", e)

    def analyze_statistics(self):
        try:
            data = self.unique_df.select_dtypes(include='number')
            print("Mean:\n", np.mean(data))
            print("\nMedian:\n", np.median(data))
            print("\nStandard Deviation:\n", np.std(data))
            print("\nVariance:\n", np.var(data))
        except Exception as e:
            print("Analysis error:\n", e)

    def compute_correlation(self):
        try:
            corr = self.unique_df.corr(numeric_only=True)
            print(corr)
            return corr
        except Exception as e:
            print("Correlation error:\n", e)

    def plot_correlation_heatmap(self):
        try:
            corr = self.unique_df.corr(numeric_only=True)
            plt.figure(figsize=(10, 6))
            sns.heatmap(corr, annot=True, cmap="coolwarm")
            plt.title("Correlation Heatmap")
            plt.show()
        except Exception as e:
            print("Heatmap error:\n", e)

    def distribution_analysis(self):
        try:
            data = self.unique_df.select_dtypes(include='number')
            skewness = data.skew()
            print("Skewness:\n", skewness)

            q1 = data.quantile(0.25)
            q3 = data.quantile(0.75)
            iqr = q3 - q1

            print("\nInterquartile Range:\n", iqr)

            outliers = {}

            for col in data.columns:
                lower = q1[col] - 1.5 * iqr[col]
                upper = q3[col] + 1.5 * iqr[col]

                outlier_count = data[(data[col] < lower) | (data[col] > upper)].shape[0]
                outliers[col] = outlier_count

            print("\nOutliers per Column:\n", outliers)

        except Exception as e:
            print("Distribution analysis error:\n", e)

    def static_graphs(self):
        try:
            self.unique_df.hist(figsize=(12, 10))
            plt.suptitle("Robot Kinematics Histograms")
            plt.show()

            plt.figure(figsize=(12, 6))
            sns.boxplot(data=self.unique_df.select_dtypes(include=['number']))
            plt.title("Robot Kinematics Boxplot")
            plt.xticks(rotation=45)
            plt.show()

            plt.figure(figsize=(8, 6))
            sns.scatterplot(x='x', y='y', data=self.unique_df)
            plt.title("End-Effector XY Trajectory")
            plt.show()

        except Exception as e:
            print("Static graph error:\n", e)

    def animate_motion_type_pie(self):
        try:
            import matplotlib.pyplot as plt
            from matplotlib.animation import FuncAnimation

            df = self.unique_df.copy()

            if df.empty:
                print("Pie animation error: unique_df is empty, cannot create animation.")
                return None

            if 'motion_type' not in df.columns:
                print("Pie animation error: 'motion_type' column not found in unique_df.")
                return None

            df['motion_type'] = df['motion_type'].astype(str).replace('nan', 'Unknown').fillna('Unknown')
            counts = df['motion_type'].value_counts()

            counts = counts[np.isfinite(counts) & (counts > 0)]
            counts = counts.astype(float)

            if counts.empty:
                print("Pie animation error: No valid 'motion_type' categories found after robust filtering.")
                plt.close('all')
                return None

            labels = counts.index.astype(str).tolist()
            pie_data_values = counts.values.tolist()

            if not pie_data_values:
                print("Pie animation error: No valid data points.")
                plt.close('all')
                return None

            if sum(pie_data_values) == 0:
                print("Pie animation error: All counts are zero.")
                plt.close('all')
                return None

            fig, ax = plt.subplots(figsize=(6, 6))
            ax.set_title("Motion Type Distribution")

            ax.pie([0.0]*len(pie_data_values), labels=labels, startangle=90)

            def update(frame):
                ax.clear()
                ax.set_title("Motion Type Distribution")
                current_frame_values = [v * frame / 100 for v in pie_data_values]
                ax.pie(current_frame_values, labels=labels, startangle=90)

            ani = FuncAnimation(fig, update, frames=100, interval=30, blit=False)

            plt.close(fig)
            return ani

        except Exception as e:
            print("Pie animation error:", e)
            return None

    def animate_motion_type_quality(self):
        try:
            df = self.unique_df.copy()
            grouped = df.groupby('motion_type')['motion_quality_score'].mean()

            categories = list(grouped.index)
            values = list(grouped.values)

            fig, ax = plt.subplots(figsize=(10, 5))

            ax.set_title("Average Motion Quality per Motion Type")
            ax.set_ylim(0, max(values) + 1)

            bars = ax.bar(categories, [0]*len(categories))

            def update(frame):
                for i, bar in enumerate(bars):
                    bar.set_height(values[i] * frame / 100)
                return bars

            ani = FuncAnimation(fig, update, frames=100, interval=30, blit=False)

            plt.close(fig)
            return ani

        except Exception as e:
            print("Animation error:", e)

    def animate_servo_bar(self):
        try:
            df = self.unique_df.copy()

            servo_cols = [col for col in df.columns if col.startswith('servo_') and col.endswith('_pos')]

            if not servo_cols:
                print("Servo bar animation error: No servo columns found.")
                return None

            min_pos = df[servo_cols].min().min()
            max_pos = df[servo_cols].max().max()

            fig, ax = plt.subplots(figsize=(10, 6))
            ax.set_title("Servo Positions Over Time")
            ax.set_xlabel("Servo")
            ax.set_ylabel("Position")
            ax.set_ylim(min_pos, max_pos)
            ax.set_xticks(range(len(servo_cols)))
            ax.set_xticklabels(servo_cols, rotation=45)

            bars = ax.bar(servo_cols, [0]*len(servo_cols))

            def update(frame):
                if frame < len(df):
                    current = df.iloc[frame][servo_cols]
                    for i, bar in enumerate(bars):
                        bar.set_height(current.iloc[i])
                return bars

            ani = FuncAnimation(fig, update, frames=len(df), interval=50, blit=False)

            plt.close(fig)
            return ani

        except Exception as e:
            print("Servo bar animation error:", e)
            return None

    def compute_repeatability_error(self, tol=0.02):
        try:
            df = self.unique_df.copy()

            df['x_bin'] = (df['x'] / tol).astype(int)
            df['y_bin'] = (df['y'] / tol).astype(int)
            df['z_bin'] = (df['z'] / tol).astype(int)

            grouped = df.groupby(['x_bin', 'y_bin', 'z_bin'])

            errors = []

            for _, group in grouped:
                if len(group) > 1:
                    center = group[['x', 'y', 'z']].mean()
                    error = np.sqrt(((group[['x', 'y', 'z']] - center) ** 2).sum(axis=1).mean())
                    errors.append(error)

            if len(errors) == 0:
                fallback_error = np.sqrt(((df[['x','y','z']] - df[['x','y','z']].mean()) ** 2).sum(axis=1).mean())
                print("\nRepeatability Error (fallback - no clusters):")
                print(fallback_error)
                return fallback_error

            overall_error = np.mean(errors)
            print("\nRepeatability Error:")
            print(overall_error)
            return overall_error

        except Exception as e:
            print("Repeatability computation failed:", e)
            return None

csv_filepath = '/content/robot_assisted_animation_dataset.csv'
system = IRBRobotKinematicsSystem(filepath=csv_filepath, last_digit=15)
system.load_data()
system.clean_data()
system.create_unique_df()

system = IRBRobotKinematicsSystem(filepath=csv_filepath, last_digit=15)

system.load_data()
system.clean_data()
system.create_unique_df()

system.compute_repeatability_error()

system.create_unique_df()
system.analyze_statistics()

system.create_unique_df()
system.distribution_analysis()

system.create_unique_df()
system.plot_correlation_heatmap()

system.static_graphs()

system = IRBRobotKinematicsSystem(filepath=csv_filepath, last_digit=15)
system.load_data()
system.clean_data()
system.create_unique_df()

ani = system.animate_motion_type_quality()
display(HTML(ani.to_jshtml()))

system = IRBRobotKinematicsSystem(filepath=csv_filepath, last_digit=15)
system.load_data()
system.clean_data()
system.create_unique_df()

ani = system.animate_servo_bar()
display(HTML(ani.to_jshtml()))

